name: GitHub Actions Demo
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 #permet de récupérer les fichiers dans git
      - run: ls -la
      - run: pip3 install pytest
      - run: pytest test_lib.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: logs.txt
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          USER: ${{ secrets.USER }}
        run: docker login -u $USER -p $PASSWORD
      - name: Build the Docker image
        run: docker build -t 77871417/myrepo .
      - name: Push the Docker image
        run: docker push 77871417/devops:latest
