name: GitHub Actions Demo
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 #permet de récupérer les fichiers dans git
      - run: ls -la
      - run: pip3 install pytest
      - run: pytest test_lib.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: logs.txt
  Build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - run: docker build -t 7871417/myrepo:latest .
     - run: docker login -u $secret.USER -p  $secret.PASSWORD
     - run: docker push 7871417/myrepo:latest
